edit pipiline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -23,9 +23,13 @@ test-job:
 check_coverage:
   stage: check_coverage
   script:
-    - COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
-    - echo "Coverage: $COVERAGE%"
-    - if [ "$COVERAGE" -lt 30 ]; then echo "Coverage is below 30%, failing the pipeline"; exit 1; fi
+    - |
+      COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
+      echo "Coverage: $COVERAGE%"
+      if [ "$COVERAGE" -lt 30 ]; then
+        echo "Coverage is below 30%, failing the pipeline"
+        exit 1
+      fi
   only:
     - merge_requests
     - master
